export const productCenterSeo = {
  title: 'Disposable Hygiene & Cleaning Products Manufacturer | JCZCARE',
  description: 'Explore six disposable hygiene, absorbent material, and cleaning product categories for wholesale, private label, and OEM/ODM manufacturing projects.',
  keywords: [
    'disposable hygiene products manufacturer',
    'OEM hygiene products supplier',
    'private label disposable products',
    'wholesale cleaning products',
  ],
};

const placeholder = (label) => ({
  image: null,
  imageAlt: `${label} product image placeholder pending approved photography`,
  imageStatus: 'placeholder',
});

const product = ({ name, slug, features, image = null, imageAlt = '', imageStatus = 'existing', imageFit = null, imagePosition = null, gallery = null, detailGallery = null }) => ({
  name,
  title: name,
  slug,
  features,
  summary: features.join('. '),
  image,
  imageAlt: imageAlt || `${name} product presentation`,
  imageStatus,
  imageFit,
  imagePosition,
  gallery,
  detailGallery,
  oem: true,
});

export const productSeries = [
  {
    slug: 'pet-training-pads',
    title: 'Pet Urine Pads',
    shortTitle: 'Pet Urine Pads',
    category: 'Absorbent Pet Hygiene',
    summary: 'Disposable urine pad formats for pet care, daily floor protection, and private-label product programs.',
    intro: 'Develop a focused pet urine pad range with configurable format, materials, functional options, print direction, and packaging.',
    image: '/images/oem/products/custom-disposable-pet-pads-premium.png',
    imageAlt: 'Packaged pet training pads with a folded product stack in a home setting',
    imageStatus: 'existing',
    featured: true,
    productTypes: ['Standard', 'Charcoal', 'Thickened Charcoal', 'Non-Slip'],
    customization: ['Custom Size', 'Custom Absorbency', 'Custom Materials', 'Printed Design', 'Private Label Packaging', 'Functional Customization'],
    products: [
      product({
        name: 'Standard Pet Urine Pads',
        slug: 'standard-pet-urine-pads',
        features: ['Standard pet urine pad format', 'Custom size, absorbency, pack count, and packaging available'],
        image: '/images/products/pet-training-pads/standard-pet-urine-pad.webp',
        imageAlt: 'Standard pet urine pads with white and blue retail packaging',
        gallery: [
          { src: '/images/products/pet-training-pads/standard-pet-urine-pad.webp', alt: 'Standard pet urine pads with white and blue retail packaging' },
          { src: '/images/products/pet-training-pads/standard-pet-urine-pad-absorbency-test.png', alt: 'Blue liquid absorbency test on a white pet urine pad' },
          { src: '/images/products/pet-training-pads/standard-pet-urine-pad-petbest-packaging.png', alt: 'PetBest pet pad packaging range in multiple sizes' },
          { src: '/images/products/pet-training-pads/rolled-absorbent-pad-rolls.png', alt: 'Rolled absorbent pet pads arranged in a clean product presentation' },
        ],
      }),
      product({
        name: 'Bamboo Charcoal Pet Urine Pads',
        slug: 'bamboo-charcoal-pet-training-pads',
        features: ['Charcoal product format', 'Custom size and packaging direction'],
        image: '/images/oem/products/custom-charcoal-pet-pad-ai.webp',
        imageAlt: 'Bamboo charcoal pet training pad product presentation',
      }),
      product({
        name: 'Black Gold Activated Carbon Pet Pads',
        slug: 'black-gold-activated-carbon-pet-pads',
        features: ['Activated-carbon pet urine pad format', 'Custom size, absorbency, and packaging direction available'],
        image: '/images/products/pet-training-pads/black-gold-activated-carbon-pet-pads.webp',
        imageAlt: 'Black gold activated carbon pet training pad retail package',
        imageFit: 'contain',
        imagePosition: 'center',
        detailGallery: [
          { src: '/images/products/pet-training-pads/black-gold-activated-carbon-pet-pads.webp', alt: 'Black gold activated carbon pet training pad retail package', title: 'Black Gold Activated Carbon Pad' },
        ],
      }),
      product({
        name: 'Thickened Bamboo Charcoal Pet Pads',
        slug: 'thickened-bamboo-charcoal-pet-pads',
        features: ['Bamboo-charcoal odor-control format', 'Thickened pad and private-label packaging direction'],
        image: '/images/products/pet-training-pads/thickened-bamboo-charcoal-pet-pads.webp',
        imageAlt: 'Thickened bamboo charcoal pet pads with retail packaging and two dogs',
        imageFit: 'contain',
        imagePosition: 'center',
      }),
      product({
        name: 'Non-Slip Pet Urine Pads',
        slug: 'adhesive-pet-training-pads',
        features: ['Non-slip backing for stable placement', 'Custom size and absorbency direction'],
        image: '/images/oem/products/custom-adhesive-pet-pad-ai.webp',
        imageAlt: 'Non-slip pet urine pads with purple retail packaging',
      }),
    ],
    seoTitle: 'Pet Urine Pads Manufacturer | OEM & Private Label',
    seoDescription: 'Explore standard, charcoal, non-slip, and antibacterial pet urine pads for OEM/ODM and private-label projects.',
  },
  {
    slug: 'pet-absorbent-paper-sheets',
    title: 'Pet Absorbent Paper Sheets',
    shortTitle: 'Urine Absorbent Paper',
    category: 'Pet Urine Absorbent Paper',
    summary: 'Plain and printed pet urine absorbent paper supplied as a standalone range for retail, private-label, and bulk sourcing programs.',
    intro: 'Source pet urine absorbent paper independently from finished pet training pads, with plain or printed surfaces, custom dimensions, absorbency direction, packaging, and bulk supply options.',
    image: '/images/oem/products/custom-absorbent-paper-ai.webp',
    imageAlt: 'Standard white pet urine absorbent paper with blue retail packaging',
    imageStatus: 'existing',
    featured: false,
    productTypes: ['Standard Absorbent Paper', 'Printed Absorbent Paper'],
    customization: ['Custom Sheet Size', 'Custom Basis Weight', 'Absorbency Direction', 'Printed Design', 'Private Label Packaging', 'Bulk Packaging'],
    products: [
      product({
        name: 'Standard Pet Urine Absorbent Paper',
        slug: 'standard-pet-urine-absorbent-paper',
        features: ['Standard white absorbent paper format', 'Custom pack count and private-label packaging available'],
        image: '/images/oem/products/custom-absorbent-paper-ai.webp',
        imageAlt: 'Standard white pet urine absorbent paper with blue retail packaging',
      }),
      product({
        name: 'Printed Pet Urine Absorbent Paper',
        slug: 'printed-pet-urine-absorbent-paper',
        features: ['Custom printed absorbent paper surface', 'Private-label retail packaging available'],
        image: '/images/products/printed-pet-urine-absorbent-paper/printed-pet-urine-absorbent-paper-showcase.webp',
        imageAlt: 'Printed pet urine absorbent paper displayed with retail packaging and a small dog',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
    ],
    seoTitle: 'Pet Urine Absorbent Paper Manufacturer | OEM & Private Label',
    seoDescription: 'Source standard and printed pet urine absorbent paper with configurable dimensions, absorbency, private-label packaging, and bulk supply options.',
  },
  {
    slug: 'pet-diapers',
    title: 'Pet Diapers',
    shortTitle: 'Pet Diapers',
    category: 'Disposable Pet Care',
    summary: 'Disposable diaper formats for male dogs, female dogs, and pull-up pet care product programs.',
    intro: 'Review the three pet diaper formats available for wholesale, private-label, and OEM/ODM project discussion.',
    image: '/images/products/pet-diapers/pet-diapers-series-cover.webp',
    imageAlt: 'Male and female pet diaper retail packages displayed on white podiums',
    imageStatus: 'existing',
    imageFit: 'cover',
    imagePosition: 'center',
    featured: false,
    productTypes: ['Male Dog Diapers', 'Female Dog Diapers', 'Pet Pull-Up Diapers'],
    customization: ['Custom Size', 'Custom Materials', 'Fit and Fastening Direction', 'Pack Count', 'Private Label Packaging'],
    products: [
      product({
        name: 'Male Dog Diapers',
        slug: 'male-dog-diapers',
        features: ['Male dog diaper format', 'Custom size and packaging direction'],
        image: '/images/products/pet-diapers/male-dog-diapers.webp',
        imageAlt: 'Male dog diapers in blue and white retail packaging',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
      product({
        name: 'Female Dog Diapers',
        slug: 'female-dog-diapers',
        features: ['Female dog diaper format', 'Custom size and packaging direction'],
        image: '/images/products/pet-diapers/female-dog-diapers.webp',
        imageAlt: 'Female dog diapers in blue and white retail packaging',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
      product({
        name: 'Pet Pull-Up Diapers',
        slug: 'pet-pull-up-diapers',
        features: ['Pull-up pet diaper format', 'Custom materials and packaging direction'],
        image: '/images/products/pet-diapers/pet-pull-up-diapers.webp',
        imageAlt: 'Disposable pet pull-up diapers in white and yellow retail packaging',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
    ],
    seoTitle: 'Pet Diapers Manufacturer | OEM Dog Diapers Supplier',
    seoDescription: 'Explore male dog diapers, female dog diapers, and pet pull-up diapers for wholesale, OEM/ODM, and private-label manufacturing projects.',
  },
  {
    slug: 'adult-underpads',
    title: 'Adult Underpads',
    shortTitle: 'Adult Underpads',
    category: 'Adult Care Protection',
    summary: 'Disposable adult underpads and adult diapers with configurable size, absorbency, materials, and private-label packaging.',
    intro: 'Review adult underpads and adult diapers for wholesale, private-label, and OEM/ODM adult-care product programs.',
    image: '/images/oem/products/adult-underpads-hero.png',
    imageAlt: 'Packaged adult nursing pads with folded and unfolded underpads',
    imageStatus: 'existing',
    featured: false,
    productTypes: ['Adult Underpads', 'Adult Diapers'],
    customization: ['Different Sizes', 'Different Absorbency Levels', 'Custom SAP and Fluff Pulp Ratios', 'Non-Slip Back Sheet', 'Custom Packaging', 'Private Label Manufacturing'],
    products: [
      product({
        name: 'Adult Underpads',
        slug: 'adult-underpads',
        features: ['Size and absorbency customization', 'Back sheet and packaging options'],
        image: '/images/oem/products/adult-underpads-hero.png',
        imageAlt: 'Packaged adult nursing pads with folded and unfolded underpads',
      }),
      product({
        name: 'Adult Diapers',
        slug: 'adult-diapers',
        features: ['Adult diaper size and absorbency options', 'Materials, fastening, and private-label packaging available'],
        image: '/images/products/adult-underpads/adult-diapers.webp',
        imageAlt: 'Blue adult diaper retail package with two folded white adult diapers in a bright bedroom',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
    ],
    seoTitle: 'Adult Underpads & Diapers Manufacturer | OEM Private Label Supplier',
    seoDescription: 'Custom adult underpads and adult diapers with size, absorbency, materials, backing, fastening, packaging, and private-label manufacturing options.',
  },
  {
    slug: 'disposable-cleaning-products',
    title: 'Disposable Cleaning Products',
    shortTitle: 'Cleaning Products',
    category: 'Single-Use Cleaning',
    summary: 'Wet wipes, disposable cleaning finger cots, gloves, and other single-use cleaning product formats.',
    intro: 'Build coordinated disposable cleaning ranges with product-format, material, packaging, and private-label options.',
    image: '/images/products/disposable-cleaning-products/disposable-cleaning-gloves-upload.png',
    imageAlt: 'Disposable cleaning products arranged for a clean product presentation',
    imageStatus: 'existing',
    featured: false,
    productTypes: ['Wet Wipes', 'Cleaning Finger Cots', 'Cleaning Gloves', 'Other Cleaning Products'],
    customization: ['Custom Product Format', 'Custom Materials', 'Custom Size', 'Pack Count', 'Private Label Packaging'],
    products: [
      product({
        name: 'Wet Wipes',
        slug: 'wet-wipes',
        features: ['Disposable wet wipe format', 'Custom materials and packaging direction'],
        image: '/images/products/disposable-cleaning-products/pet-cleaning-wet-wipes.webp',
        imageAlt: 'Pet cleaning wet wipes in green retail packaging',
        imageFit: 'contain',
        imagePosition: 'center',
      }),
      product({
        name: 'Disposable Cleaning Finger Cots',
        slug: 'disposable-cleaning-finger-cots',
        features: ['Disposable finger-cot format', 'Custom size and packaging direction'],
        image: '/images/products/disposable-cleaning-products/disposable-cleaning-finger-cots.webp',
        imageAlt: 'Two-sided pet dental cleaning finger wipes with blue and white retail tub',
        imageFit: 'cover',
        imagePosition: '70% center',
      }),
      product({ name: 'Disposable Cleaning Gloves', slug: 'disposable-cleaning-gloves', features: ['Disposable cleaning glove format', 'Private-label packaging available'], image: '/images/products/disposable-cleaning-products/disposable-cleaning-gloves-upload.png', imageAlt: 'Disposable cleaning gloves product presentation' }),
    ],
    seoTitle: 'Disposable Cleaning Products Manufacturer | OEM Supplier',
    seoDescription: 'Explore wet wipes, disposable cleaning finger cots, and disposable cleaning gloves for OEM and private-label projects.',
  },
  {
    slug: 'garbage-bags',
    title: 'Garbage Bags',
    shortTitle: 'Garbage Bags',
    category: 'Disposable Bag Products',
    summary: 'Standard, multicolor, printed, dispenser-set, color-block, degradable, and fully biodegradable garbage bag formats for wholesale and private-label programs.',
    intro: 'Discuss material, dimensions, bag format, print direction, and packaging without unconfirmed environmental certification claims.',
    image: '/images/products/garbage-bags/garbage-bags-series-cover.webp',
    imageAlt: 'Colorful garbage bag rolls displayed beside premium retail packaging',
    imageStatus: 'existing',
    featured: false,
    productTypes: ['Standard', 'Multicolor', 'Printed', 'Dispenser Set', 'Color-Block', 'Degradable', 'Fully Biodegradable'],
    customization: ['Custom Size', 'Material Direction', 'Bag Format', 'Printed Design', 'Private Label Packaging'],
    products: [
      product({
        name: 'Standard Garbage Bags',
        slug: 'standard-garbage-bags',
        features: ['Standard garbage bag format', 'Custom size and packaging direction'],
        image: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-06.webp',
        imageAlt: 'Standard pet waste bags shown with retail packaging and a bone-shaped dispenser',
        gallery: [
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-06.webp', alt: 'Standard pet waste bags shown with retail packaging and a bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-01.webp', alt: 'Printed yellow pet waste bag pulled from a bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-02.webp', alt: 'Standard pet waste bag roll and dispenser shown from a side angle' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-03.webp', alt: 'Pet waste bag roll, dispenser and detachable cap shown from above' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-04.webp', alt: 'Bone-shaped pet waste bag dispenser with the bag opening visible' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-05.webp', alt: 'Retail packaging for standard pet waste bags and dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-07.webp', alt: 'Blue pet waste bag dispenser shown with retail packaging and an opened bag' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-08.webp', alt: 'Blue pet waste bag retail package shown beside the dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-09.webp', alt: 'Pink pet waste bag retail package with a bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-10.webp', alt: 'Blue pet waste bag retail package with a bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-11.webp', alt: 'Pink and blue pet waste bag retail packages shown together' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-01.webp', alt: 'Printed yellow pet waste bag pulled from a bone-shaped dispenser', title: 'Bag Dispensing' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-02.webp', alt: 'Standard pet waste bag roll and dispenser shown from a side angle', title: 'Dispenser Side View' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-03.webp', alt: 'Pet waste bag roll, dispenser and detachable cap shown from above', title: 'Roll & Refill Structure' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-04.webp', alt: 'Bone-shaped pet waste bag dispenser with the bag opening visible', title: 'Bag Opening Detail' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-05.webp', alt: 'Retail packaging for standard pet waste bags and dispenser', title: 'Retail Packaging' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-06.webp', alt: 'Standard pet waste bags shown with retail packaging and a bone-shaped dispenser', title: 'Product Set Presentation' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-07.webp', alt: 'Blue pet waste bag dispenser shown with retail packaging and an opened bag', title: 'Blue Color Variant' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-08.webp', alt: 'Blue pet waste bag retail package shown beside the dispenser', title: 'Blue Packaging Variant' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-09.webp', alt: 'Pink pet waste bag retail package with a bone-shaped dispenser', title: 'Pink Color Variant' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-10.webp', alt: 'Blue pet waste bag retail package with a bone-shaped dispenser', title: 'Blue Product Variant' },
          { src: '/images/products/garbage-bags/standard-garbage-bags/standard-garbage-bags-11.webp', alt: 'Pink and blue pet waste bag retail packages shown together', title: 'Color Range Presentation' },
        ],
      }),
      product({
        name: 'Multicolor Garbage Bags',
        slug: 'multicolor-garbage-bags',
        features: ['Multicolor garbage bag roll format', 'Custom colors, sizes, and packaging direction available'],
        image: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-02.webp',
        imageAlt: 'Multicolor garbage bag rolls displayed in retail packaging',
        gallery: [
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-02.webp', alt: 'Multicolor garbage bag rolls displayed in retail packaging' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-01.webp', alt: 'Orange, blue, and green garbage bag rolls standing upright' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-03.webp', alt: 'Retail package with orange, blue, and pink garbage bag rolls' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-04.webp', alt: 'Multicolor garbage bag retail packaging with loose rolls' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-05.webp', alt: 'Orange, green, and blue garbage bag rolls shown from the front' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-06.webp', alt: 'Orange, green, and blue garbage bag rolls arranged side by side' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-07.webp', alt: 'Orange, green, and blue garbage bag rolls shown at an angle' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-08.webp', alt: 'Close-up of orange, green, and blue garbage bag rolls' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-09.webp', alt: 'Orange garbage bag roll opened to show the bag material' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-10.webp', alt: 'Orange garbage bag being separated at the perforation' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-02.webp', alt: 'Multicolor garbage bag rolls displayed in retail packaging', title: 'Retail Packaging' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-01.webp', alt: 'Orange, blue, and green garbage bag rolls standing upright', title: 'Color Range' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-03.webp', alt: 'Retail package with orange, blue, and pink garbage bag rolls', title: 'Pack Format' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-04.webp', alt: 'Multicolor garbage bag retail packaging with loose rolls', title: 'Packaging and Loose Rolls' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-05.webp', alt: 'Orange, green, and blue garbage bag rolls shown from the front', title: 'Front Roll View' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-06.webp', alt: 'Orange, green, and blue garbage bag rolls arranged side by side', title: 'Roll Arrangement' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-07.webp', alt: 'Orange, green, and blue garbage bag rolls shown at an angle', title: 'Angled Product View' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-08.webp', alt: 'Close-up of orange, green, and blue garbage bag rolls', title: 'Roll Detail' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-09.webp', alt: 'Orange garbage bag roll opened to show the bag material', title: 'Bag Material Detail' },
          { src: '/images/products/garbage-bags/multicolor-garbage-bags/multicolor-garbage-bags-10.webp', alt: 'Orange garbage bag being separated at the perforation', title: 'Perforation Detail' },
        ],
      }),
      product({
        name: 'Printed Pet Waste Bags',
        slug: 'printed-pet-waste-bags',
        features: ['Printed pet waste bag roll format', 'Custom colors, sizes, and packaging direction available'],
        image: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-01.webp',
        imageAlt: 'Yellow printed pet waste bag rolls displayed with retail packaging',
        gallery: [
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-01.webp', alt: 'Yellow printed pet waste bag rolls displayed with retail packaging' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-02.webp', alt: 'Yellow, green, and white pet waste bag rolls shown together' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-03.webp', alt: 'Assorted yellow, green, and white printed pet waste bag rolls' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-04.webp', alt: 'Printed yellow and green pet waste bags with an unfolded green bag' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-05.webp', alt: 'Yellow, white, and green pet waste bag rolls in a front view' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-06.webp', alt: 'Mixed printed and solid green pet waste bag rolls' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-07.webp', alt: 'Yellow, white, and green pet waste bag rolls with a green roll detail' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-08.webp', alt: 'Green pet waste bag rolls displayed beside a retail box' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-09.webp', alt: 'White pet waste bag rolls displayed beside a retail box' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-10.webp', alt: 'Green pet waste bag rolls with one upright roll' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-11.webp', alt: 'Four green pet waste bag rolls arranged in a row' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-12.webp', alt: 'Green pet waste bag rolls with an unfolded bag' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-13.webp', alt: 'Green pet waste bag rolls shown in a close-up arrangement' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-01.webp', alt: 'Yellow printed pet waste bag rolls displayed with retail packaging', title: 'Retail Packaging' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-02.webp', alt: 'Yellow, green, and white pet waste bag rolls shown together', title: 'Color Range' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-03.webp', alt: 'Assorted yellow, green, and white printed pet waste bag rolls', title: 'Assorted Roll Set' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-04.webp', alt: 'Printed yellow and green pet waste bags with an unfolded green bag', title: 'Unfolded Bag View' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-05.webp', alt: 'Yellow, white, and green pet waste bag rolls in a front view', title: 'Front Roll View' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-06.webp', alt: 'Mixed printed and solid green pet waste bag rolls', title: 'Mixed Material Presentation' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-07.webp', alt: 'Yellow, white, and green pet waste bag rolls with a green roll detail', title: 'Roll Detail' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-08.webp', alt: 'Green pet waste bag rolls displayed beside a retail box', title: 'Green Retail Set' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-09.webp', alt: 'White pet waste bag rolls displayed beside a retail box', title: 'White Retail Set' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-10.webp', alt: 'Green pet waste bag rolls with one upright roll', title: 'Upright Roll Format' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-11.webp', alt: 'Four green pet waste bag rolls arranged in a row', title: 'Multi-Roll Presentation' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-12.webp', alt: 'Green pet waste bag rolls with an unfolded bag', title: 'Bag Opening Detail' },
          { src: '/images/products/garbage-bags/printed-pet-waste-bags/printed-pet-waste-bags-13.webp', alt: 'Green pet waste bag rolls shown in a close-up arrangement', title: 'Close-Up Product View' },
        ],
      }),
      product({
        name: 'Pet Waste Bags with Dispenser',
        slug: 'pet-waste-bags-with-dispenser',
        features: ['Printed pet waste bag rolls with a matching dispenser', 'Custom colors, patterns, and packaging direction available'],
        image: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-01.webp',
        imageAlt: 'Yellow printed pet waste bag rolls with a matching bone-shaped dispenser',
        gallery: [
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-01.webp', alt: 'Yellow printed pet waste bag rolls with a matching bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-03.webp', alt: 'Yellow striped pet waste bag rolls with a matching dispenser' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-05.webp', alt: 'Pink heart-patterned pet waste bag rolls arranged together' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-08.webp', alt: 'Pink heart-patterned pet waste bag roll shown unfolded' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-10.webp', alt: 'Pink heart-patterned pet waste bag rolls with an open bag' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-16.webp', alt: 'Blue heart-patterned pet waste bag roll shown unfolded' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-20.webp', alt: 'Blue heart-patterned pet waste bag rolls in a close-up arrangement' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-23.webp', alt: 'Blue heart-patterned pet waste bag rolls with an open bag' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-26.webp', alt: 'Cyan pet waste bag rolls with a matching bone-shaped dispenser' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-28.webp', alt: 'Green paw-patterned pet waste bag rolls with a matching dispenser' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-01.webp', alt: 'Yellow printed pet waste bag rolls with a matching bone-shaped dispenser', title: 'Yellow Dispenser Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-02.webp', alt: 'Yellow pet waste bag rolls with a matching dispenser', title: 'Yellow Roll Variant' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-03.webp', alt: 'Yellow striped pet waste bag rolls with a matching dispenser', title: 'Yellow Stripe Variant' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-04.webp', alt: 'Pink heart-patterned pet waste bag roll standing upright', title: 'Pink Single Roll' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-05.webp', alt: 'Pink heart-patterned pet waste bag rolls arranged together', title: 'Pink Roll Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-06.webp', alt: 'Pink heart-patterned pet waste bag rolls stacked together', title: 'Pink Stacked Rolls' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-07.webp', alt: 'Pink heart-patterned pet waste bag rolls shown at an angle', title: 'Pink Angled View' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-08.webp', alt: 'Pink heart-patterned pet waste bag roll shown unfolded', title: 'Pink Open Bag' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-09.webp', alt: 'Pink heart-patterned pet waste bag rolls arranged in a product set', title: 'Pink Product Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-10.webp', alt: 'Pink heart-patterned pet waste bag rolls with an open bag', title: 'Pink Open Roll Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-11.webp', alt: 'Pink heart-patterned pet waste bag rolls shown in a close-up', title: 'Pink Close-Up' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-12.webp', alt: 'Pink heart-patterned pet waste bag roll with the bag unfolded', title: 'Pink Bag Material' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-13.webp', alt: 'Green pet waste bag rolls arranged in a pyramid', title: 'Green Roll Pyramid' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-14.webp', alt: 'Green pet waste bag rolls arranged in a side stack', title: 'Green Roll Stack' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-15.webp', alt: 'Green pet waste bag rolls arranged in a front-facing pyramid', title: 'Green Front Arrangement' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-16.webp', alt: 'Blue heart-patterned pet waste bag roll shown unfolded', title: 'Blue Open Bag' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-17.webp', alt: 'Blue heart-patterned pet waste bags shown in an open presentation', title: 'Blue Bag Presentation' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-18.webp', alt: 'Blue heart-patterned pet waste bag roll standing upright', title: 'Blue Single Roll' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-19.webp', alt: 'Blue heart-patterned pet waste bag rolls arranged together', title: 'Blue Roll Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-20.webp', alt: 'Blue heart-patterned pet waste bag rolls in a close-up arrangement', title: 'Blue Roll Detail' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-21.webp', alt: 'Blue heart-patterned pet waste bag rolls shown at an angle', title: 'Blue Angled View' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-22.webp', alt: 'Blue heart-patterned pet waste bag rolls with upright and horizontal formats', title: 'Blue Mixed Arrangement' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-23.webp', alt: 'Blue heart-patterned pet waste bag rolls with an open bag', title: 'Blue Open Roll Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-24.webp', alt: 'Blue heart-patterned pet waste bag rolls arranged in a product set', title: 'Blue Product Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-25.webp', alt: 'Blue heart-patterned pet waste bag rolls with an open roll', title: 'Blue Open Roll Detail' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-26.webp', alt: 'Cyan pet waste bag rolls with a matching bone-shaped dispenser', title: 'Cyan Dispenser Set' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-27.webp', alt: 'Cyan striped pet waste bag rolls with a matching dispenser', title: 'Cyan Stripe Variant' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-28.webp', alt: 'Green paw-patterned pet waste bag rolls with a matching dispenser', title: 'Green Paw Variant' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-29.webp', alt: 'Green striped pet waste bag rolls with a matching dispenser', title: 'Green Stripe Variant' },
          { src: '/images/products/garbage-bags/pet-waste-bags-with-dispenser/pet-waste-bags-with-dispenser-30.webp', alt: 'Solid green pet waste bag rolls with a matching dispenser', title: 'Green Solid Variant' },
        ],
      }),
      product({
        name: 'Color-Block Pet Waste Bags',
        slug: 'color-block-pet-waste-bags',
        features: ['Two-color pet waste bag roll format', 'Custom color combinations, sizes, and packaging direction available'],
        image: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-01.webp',
        imageAlt: 'Purple and teal pet waste bag rolls displayed in retail packaging',
        gallery: [
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-01.webp', alt: 'Purple and teal pet waste bag rolls displayed in retail packaging' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-02.webp', alt: 'Purple and lime pet waste bag rolls with a retail pack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-04.webp', alt: 'Purple and lime pet waste bag rolls in a hanging package' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-07.webp', alt: 'Purple and teal pet waste bag rolls arranged in a pyramid' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-09.webp', alt: 'Purple and teal pet waste bag rolls arranged in a layered stack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-11.webp', alt: 'Purple and teal pet waste bag rolls with a loose teal roll' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-14.webp', alt: 'Purple and teal pet waste bag rolls lined up together' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-16.webp', alt: 'Teal pet waste bag roll shown unfolded' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-19.webp', alt: 'Teal and purple pet waste bags shown unfolded together' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-20.webp', alt: 'Purple and lime pet waste bag rolls in retail packaging' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-01.webp', alt: 'Purple and teal pet waste bag rolls displayed in retail packaging', title: 'Retail Package' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-02.webp', alt: 'Purple and lime pet waste bag rolls with a retail pack', title: 'Loose Roll Set' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-03.webp', alt: 'Purple and lime pet waste bag rolls shown beside a retail pack', title: 'Pack and Roll View' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-04.webp', alt: 'Purple and lime pet waste bag rolls in a hanging package', title: 'Hanging Pack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-05.webp', alt: 'Purple and teal pet waste bag rolls in a front-facing box package', title: 'Box Package Front' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-06.webp', alt: 'Purple and teal pet waste bag box package shown at an angle', title: 'Box Package Angle' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-07.webp', alt: 'Purple and teal pet waste bag rolls arranged in a pyramid', title: 'Pyramid Roll Stack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-08.webp', alt: 'Purple and teal pet waste bag rolls arranged in a layered stack', title: 'Layered Roll Stack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-09.webp', alt: 'Purple and teal pet waste bag rolls arranged in a compact stack', title: 'Compact Roll Stack' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-10.webp', alt: 'Purple and teal pet waste bag rolls shown with one upright teal roll', title: 'Upright Roll Variant' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-11.webp', alt: 'Purple and teal pet waste bag rolls with a loose teal roll', title: 'Loose Roll Detail' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-12.webp', alt: 'Purple and teal pet waste bag rolls with an unfolded teal bag', title: 'Teal Open Bag' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-13.webp', alt: 'Purple and teal pet waste bag rolls arranged in a diagonal row', title: 'Diagonal Roll Row' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-14.webp', alt: 'Purple and teal pet waste bag rolls lined up together', title: 'Color Lineup' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-15.webp', alt: 'Purple and teal pet waste bag rolls in a mixed standing arrangement', title: 'Mixed Standing Set' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-16.webp', alt: 'Teal pet waste bag roll shown unfolded', title: 'Teal Material View' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-17.webp', alt: 'Teal pet waste bag roll shown with the bag spread open', title: 'Teal Open Bag Detail' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-18.webp', alt: 'Teal pet waste bag shown separated at the perforation', title: 'Perforation Detail' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-19.webp', alt: 'Teal and purple pet waste bags shown unfolded together', title: 'Two-Color Open Bags' },
          { src: '/images/products/garbage-bags/color-block-pet-waste-bags/color-block-pet-waste-bags-20.webp', alt: 'Purple and lime pet waste bag rolls in retail packaging', title: 'Retail Pack Variant' },
        ],
      }),
      product({
        name: 'Waste Bag Dispenser Kits',
        slug: 'waste-bag-dispenser-kits',
        features: ['Retail-ready waste bag dispenser kit', 'Custom dispenser colors, bag colors, and packaging direction available'],
        image: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-01.webp',
        imageAlt: 'Pet waste bag rolls with a compact dispenser shown in retail packaging',
        gallery: [
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-01.webp', alt: 'Pet waste bag rolls with a compact dispenser shown in retail packaging' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-02.webp', alt: 'Pink and yellow waste bag dispenser rolls shown together' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-03.webp', alt: 'Cyan and purple waste bag dispenser kit in retail packaging' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-04.webp', alt: 'Standalone pink waste bag dispenser with a matching roll' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-05.webp', alt: 'Waste bag being pulled from a compact dispenser' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-06.webp', alt: 'Lime and cyan waste bag dispenser kit in retail packaging' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-08.webp', alt: 'Grey and black waste bag dispenser retail package' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-10.webp', alt: 'Teal waste bag dispenser kit shown in retail packaging' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-13.webp', alt: 'Grey dispenser with an opened waste bag' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-16.webp', alt: 'Grey dispenser with matching waste bag rolls' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-01.webp', alt: 'Pet waste bag rolls with a compact dispenser shown in retail packaging', title: 'Product Set Presentation' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-02.webp', alt: 'Pink and yellow waste bag dispenser rolls shown together', title: 'Pink and Yellow Variant' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-03.webp', alt: 'Cyan and purple waste bag dispenser kit in retail packaging', title: 'Cyan and Purple Variant' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-04.webp', alt: 'Standalone pink waste bag dispenser with a matching roll', title: 'Pink Dispenser View' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-05.webp', alt: 'Waste bag being pulled from a compact dispenser', title: 'Dispensing Use' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-06.webp', alt: 'Lime and cyan waste bag dispenser kit in retail packaging', title: 'Lime and Cyan Variant' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-07.webp', alt: 'Waste bag dispenser kit shown from a second retail angle', title: 'Retail Angle' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-08.webp', alt: 'Grey and black waste bag dispenser retail package', title: 'Grey and Black Packaging' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-09.webp', alt: 'Waste bag dispenser kit shown with its packaged rolls', title: 'Packaged Roll Detail' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-10.webp', alt: 'Teal waste bag dispenser kit shown in retail packaging', title: 'Teal Packaging Variant' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-11.webp', alt: 'Waste bag dispenser and roll shown in a close-up view', title: 'Close-Up Product View' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-12.webp', alt: 'Waste bag roll and dispenser shown from the side', title: 'Side Product View' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-13.webp', alt: 'Grey dispenser with an opened waste bag', title: 'Open Bag Detail' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-14.webp', alt: 'Grey waste bag dispenser shown with a matching roll', title: 'Grey Dispenser Variant' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-15.webp', alt: 'Grey dispenser kit with packaged waste bag rolls', title: 'Grey Kit Presentation' },
          { src: '/images/products/garbage-bags/waste-bag-dispenser-kits/waste-bag-dispenser-kits-16.webp', alt: 'Grey dispenser with matching waste bag rolls', title: 'Grey Roll Set' },
        ],
      }),
      product({
        name: 'Degradable Garbage Bags',
        slug: 'degradable-garbage-bags',
        features: ['Degradable product format', 'Material specification requires project confirmation'],
        image: '/images/products/garbage-bags/degradable-garbage-bag-hero.webp',
        imageAlt: 'Blue printed pet waste bag roll displayed beside a retail box',
        imagePosition: 'center',
        gallery: [
          { src: '/images/products/garbage-bags/degradable-garbage-bag-hero.webp', alt: 'Blue printed pet waste bag roll displayed beside a retail box' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-02.webp', alt: 'Blue and pink printed pet waste bag design options' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-03.webp', alt: 'Thick leak-resistant printed pet waste bag in use' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-04.webp', alt: 'Degradable pet waste bag shown in a green outdoor setting' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-05.webp', alt: 'Perforated pet waste bag being separated by hand' },
        ],
        detailGallery: [
          { src: '/images/products/garbage-bags/degradable-garbage-bag-03.webp', alt: 'Thick leak-resistant printed pet waste bag in use', title: 'Material & Leak Protection' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-04.webp', alt: 'Degradable pet waste bag shown in a green outdoor setting', title: 'Degradable Format Presentation' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-02.webp', alt: 'Blue and pink printed pet waste bag design options', title: 'Printed Design Options' },
          { src: '/images/products/garbage-bags/degradable-garbage-bag-05.webp', alt: 'Perforated pet waste bag being separated by hand', title: 'Easy-Tear Perforation' },
        ],
      }),
      product({
        name: 'Fully Biodegradable Garbage Bags',
        slug: 'fully-biodegradable-garbage-bags',
        features: ['Fully biodegradable product format', 'Material specification requires project confirmation'],
        image: '/images/products/garbage-bags/fully-biodegradable-garbage-bags.webp',
        imageAlt: 'Fully biodegradable green garbage bags with a roll and kraft paper packaging',
        imageFit: 'cover',
        imagePosition: 'center',
      }),
    ],
    seoTitle: 'Garbage Bags Manufacturer | OEM & Private Label Supplier',
    seoDescription: 'Explore standard, multicolor, printed, degradable, and fully biodegradable garbage bags with custom size, format, print, and private-label packaging options.',
  },
];

export const primaryProductCatalog = productSeries;

export const uploadedProductLines = productSeries.flatMap((series) => series.products.map((item) => ({
  ...item,
  title: item.name,
  category: series.title,
  intro: item.features.join('. '),
  href: `/products/${series.slug}/${item.slug}`,
  seriesSlug: series.slug,
})));

export const getProductSeries = (slug) => productSeries.find((series) => series.slug === slug) || null;

export const getSeriesProduct = (seriesSlug, productSlug) => {
  const series = getProductSeries(seriesSlug);
  const item = series?.products.find((entry) => entry.slug === productSlug) || null;
  return item ? { ...item, series } : null;
};

export const getCatalogProduct = (slug) => getProductSeries(slug);

export const buildProductQuoteHref = (series, item = null) => {
  const params = new URLSearchParams({
    productCategory: series.title,
    product: item?.name || series.title,
  });

  if (item) {
    params.set('productName', item.name);
  }

  return `/request-product-plan?${params.toString()}`;
};
